from app.engine.definitions.recipe_definition import Recipe


RECIPES = {
    "press_iron_sheet": Recipe(
        id="press_iron_sheet",
        name="Press Iron Sheet",
        required_machines=["mechanical_press"],
        duration=5.0,
        input_items={"iron_ingot": 1},
        output_items={"iron_sheet": 1},
    ),
    "press_copper_sheet": Recipe(
        id="press_copper_sheet",
        name="Press Copper Sheet",
        required_machines=["mechanical_press"],
        duration=5.0,
        input_items={"copper_ingot": 1},
        output_items={"copper_sheet": 1},
    ),
    "press_iron_plate": Recipe(
        id="press_iron_plate",
        name="Press Iron Plate",
        required_machines=["mechanical_press"],
        duration=5.0,
        input_items={"iron_sheet": 1},
        output_items={"iron_plate": 1},
    ),
    "press_copper_plate": Recipe(
        id="press_copper_plate",
        name="Press Copper Plate",
        required_machines=["mechanical_press"],
        duration=5.0,
        input_items={"copper_sheet": 1},
        output_items={"copper_plate": 1},
    ),
    "press_iron_bolt": Recipe(
        id="press_iron_bolt",
        name="Press Iron Bolt",
        required_machines=["mechanical_press"],
        duration=5.0,
        input_items={"iron_plate": 1},
        output_items={"iron_bolt": 2},
    ),
    "press_copper_wire": Recipe(
        id="press_copper_wire",
        name="Press Copper Wire",
        required_machines=["mechanical_press"],
        duration=5.0,
        input_items={"copper_plate": 1},
        output_items={"copper_wire": 2},
    ),
    "crush_raw_iron": Recipe(
        id="crush_raw_iron",
        name="Crush Raw Iron",
        required_machines=["crushing_wheel"],
        duration=5.0,
        input_items={"raw_iron": 1},
        output_items={"crushed_iron": 1},
    ),
    "crush_raw_copper": Recipe(
        id="crush_raw_copper",
        name="Crush Raw Copper",
        required_machines=["crushing_wheel"],
        duration=5.0,
        input_items={"raw_copper": 1},
        output_items={"crushed_copper": 1},
    ),
    "crush_stone": Recipe(
        id="crush_stone",
        name="Crush Stone",
        required_machines=["crushing_wheel"],
        duration=5.0,
        input_items={"stone": 1},
        output_items={"gravel": 1},
    ),
    "crush_gravel": Recipe(
        id="crush_gravel",
        name="Crush Gravel",
        required_machines=["crushing_wheel"],
        duration=5.0,
        input_items={"gravel": 1},
        output_items={"sand": 1},
    ),
    "crush_andesite": Recipe(
        id="crush_andesite",
        name="Crush Andesite",
        required_machines=["crushing_wheel"],
        duration=5.0,
        input_items={"andesite": 1},
        output_items={"crushed_andesite": 1},
    ),
    "smelt_crushed_iron": Recipe(
        id="smelt_crushed_iron",
        name="Smelt Crushed Iron",
        required_machines=["mechanical_smelter"],
        duration=5.0,
        input_items={"crushed_iron": 1},
        output_items={"iron_ingot": 1},
    ),
    "smelt_crushed_copper": Recipe(
        id="smelt_crushed_copper",
        name="Smelt Crushed Copper",
        required_machines=["mechanical_smelter"],
        duration=5.0,
        input_items={"crushed_copper": 1},
        output_items={"copper_ingot": 1},
    ),
    "smelt_sand_to_glass": Recipe(
        id="smelt_sand_to_glass",
        name="Smelt Sand To Glass",
        required_machines=["mechanical_smelter"],
        duration=5.0,
        input_items={"sand": 1},
        output_items={"glass": 1},
    ),
    "smelt_clay_to_brick": Recipe(
        id="smelt_clay_to_brick",
        name="Smelt Clay To Brick",
        required_machines=["mechanical_smelter"],
        duration=5.0,
        input_items={"clay": 1},
        output_items={"brick": 1},
    ),
    "smelt_cobblestone": Recipe(
        id="smelt_cobblestone",
        name="Smelt Cobblestone",
        required_machines=["mechanical_smelter"],
        duration=5.0,
        input_items={"cobblestone": 1},
        output_items={"stone": 1},
    ),
    "mix_andesite_alloy": Recipe(
        id="mix_andesite_alloy",
        name="Mix Andesite Alloy",
        required_machines=["mechanical_mixer"],
        duration=5.0,
        input_items={"iron_nugget": 1, "andesite": 1},
        output_items={"andesite_alloy": 1},
    ),
    "mix_conductive_alloy": Recipe(
        id="mix_conductive_alloy",
        name="Mix Conductive Alloy",
        required_machines=["mechanical_mixer"],
        duration=5.0,
        input_items={"copper_sheet": 1, "redstone": 1},
        output_items={"conductive_alloy": 1},
    ),
    "mix_construction_blend": Recipe(
        id="mix_construction_blend",
        name="Mix Construction Blend",
        required_machines=["mechanical_mixer"],
        duration=5.0,
        input_items={"gravel": 1, "sand": 1, "clay": 1},
        output_items={"construction_blend": 1},
    ),
    "mix_industrial_compound": Recipe(
        id="mix_industrial_compound",
        name="Mix Industrial Compound",
        required_machines=["mechanical_mixer"],
        duration=5.0,
        input_items={"crushed_andesite": 1, "iron_sheet": 1},
        output_items={"industrial_compound": 1},
    ),
    "mix_machine_base": Recipe(
        id="mix_machine_base",
        name="Mix Machine Base",
        required_machines=["mechanical_mixer"],
        duration=5.0,
        input_items={"iron_sheet": 1, "andesite_alloy": 1},
        output_items={"machine_base": 1},
    ),
    "assemble_shaft": Recipe(
        id="assemble_shaft",
        name="Assemble Shaft",
        required_machines=["mechanical_assembler"],
        duration=5.0,
        input_items={"andesite_alloy": 1},
        output_items={"shaft": 2},
    ),
    "assemble_cogwheel": Recipe(
        id="assemble_cogwheel",
        name="Assemble Cogwheel",
        required_machines=["mechanical_assembler"],
        duration=5.0,
        input_items={"shaft": 1, "plank": 1},
        output_items={"cogwheel": 1},
    ),
    "assemble_large_cogwheel": Recipe(
        id="assemble_large_cogwheel",
        name="Assemble Large Cogwheel",
        required_machines=["mechanical_assembler"],
        duration=5.0,
        input_items={"cogwheel": 1, "plank": 1},
        output_items={"large_cogwheel": 1},
    ),
    "assemble_machine_parts": Recipe(
        id="assemble_machine_parts",
        name="Assemble Machine Parts",
        required_machines=["mechanical_assembler"],
        duration=5.0,
        input_items={"iron_sheet": 1, "shaft": 1},
        output_items={"machine_parts": 1},
    ),
    "assemble_basic_mechanism": Recipe(
        id="assemble_basic_mechanism",
        name="Assemble Basic Mechanism",
        required_machines=["mechanical_assembler"],
        duration=5.0,
        input_items={"machine_parts": 1, "cogwheel": 1},
        output_items={"basic_mechanism": 1},
    ),
}
