from app.engine.definitions.resource_node_definition import ResourceNodeDefinition


RESOURCE_NODE_DEFINITIONS = {
    "iron_deposit": ResourceNodeDefinition(
        id="iron_deposit",
        name="Iron Deposit",
        resource_type="raw_iron",
        default_richness=1,
        default_hardness=1.0,
        default_required_machine_level=1,
        min_stock=100,
        max_stock=5000,
        traits=["ore"],
        icon="ore",
        visual_key="iron_deposit",
    ),
    "copper_deposit": ResourceNodeDefinition(
        id="copper_deposit",
        name="Copper Deposit",
        resource_type="raw_copper",
        default_richness=1,
        default_hardness=1.0,
        default_required_machine_level=1,
        min_stock=100,
        max_stock=5000,
        traits=["ore"],
        icon="ore",
        visual_key="copper_deposit",
    ),
    "coal_vein": ResourceNodeDefinition(
        id="coal_vein",
        name="Coal Vein",
        resource_type="coal",
        default_richness=1,
        default_hardness=1.0,
        default_required_machine_level=1,
        min_stock=100,
        max_stock=5000,
        traits=["ore", "fuel"],
        icon="coal",
        visual_key="coal_vein",
    ),
    "stone_outcrop": ResourceNodeDefinition(
        id="stone_outcrop",
        name="Stone Outcrop",
        resource_type="stone",
        default_richness=1,
        default_hardness=1.0,
        default_required_machine_level=1,
        min_stock=100,
        max_stock=8000,
        traits=["stone"],
        icon="stone",
        visual_key="stone_outcrop",
    ),
    "forest": ResourceNodeDefinition(
        id="forest",
        name="Forest",
        resource_type="wood",
        can_be_infinite=True,
        default_richness=1,
        default_hardness=1.0,
        default_required_machine_level=1,
        traits=["organic"],
        icon="forest",
        visual_key="forest",
    ),
    "water_source": ResourceNodeDefinition(
        id="water_source",
        name="Water Source",
        resource_type="water",
        can_be_infinite=True,
        default_richness=1,
        default_hardness=1.0,
        default_required_machine_level=1,
        traits=["fluid"],
        icon="water",
        visual_key="water_source",
    ),
}
